version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/examples"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/test"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
