#region License

/*
 * Copyright 2002-2008 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#endregion

#if (!NET_1_0 && !MONO)

#region Imports

using System.EnterpriseServices;
using Spring.Context.Support;

#endregion

namespace Spring.EnterpriseServices
{
    /// <summary>
    /// Handles loading of &lt;spring/context&gt; configuration sections for <see cref="ServicedComponent"/>s 
    /// generated by <see cref="EnterpriseServicesExporter"/>.
    /// </summary>
    /// <author>Erich Eichinger</author>
    public class ServicedComponentContextHandler : ContextHandler
    {}
}

#endif