using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyConfigurationAttribute("net-2.0.win32; debug")]
[assembly: AssemblyProductAttribute("Spring.NET Framework 1.1.2 for .NET 2.0")]
[assembly: AssemblyCompanyAttribute("SpringSource")]
[assembly: AssemblyCopyrightAttribute("Copyright 2002-2008 Spring.NET Framework Team.")]
[assembly: AssemblyTrademarkAttribute("Apache License, Version 2.0")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("1.1.2.20148")]
[assembly: AssemblyDelaySignAttribute(false)]

